name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
      - 'specification.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - 'specification.md'
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.10' 

    - run: pip install -r requirements.txt

    - uses: open-policy-agent/setup-opa@b2b258e089860efaadaaf71bf6e3aecb4a3eeff1 # v2.4.0
      with:
        version: 1.21.0

    - run: pytest